// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package permission_node

// Fill with you ideas below.
const (
	// 禁用状态
	StatusDisabled = 0
	// 启用状态
	StatusEnabled = 1
)